version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 20
  versioning-strategy: increase
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
